#!/usr/bin/env sh

# remove old serverauth files (except newest one)
ls -at ~ | grep ^.serverauth.* | perl -ne 'next unless $l++; chomp and unlink'

# while loop allows to restart dwm without killing all windows
while true; do
	. ~/config/local_config.sh

	# layout
	echo dvorak > ~/.kblayout
	kbtgl

	# caps lock repat
	xset r 66

	# disable screen blacking
	xset s off -dpms

	fehbg
	xcompmgr &

	pkill xbindkeys
	xbindkeys

	pkill dunst
	dunst &

	pkill -u $USER -f pcrd
	pcrctl run daemon

	if [ -f "$HOME/.Xresources" ]; then
		xrdb "$HOME/.Xresources"
	fi

	dwm
done

