#!/usr/bin/env sh

# remove old serverauth files (except this one)
find ~ -maxdepth 1 | grep /.serverauth.* | grep -v $$ | perl -ne 'chomp and unlink'

# while loop allows to restart dwm without killing all windows
while true; do
	. ~/config/local_config.sh

	# layout
	echo dvorak > ~/.kblayout
	kbtgl

	# caps lock repat
	xset r 66

	# disable screen blacking
	xset s off -dpms

	pkill xbindkeys
	xbindkeys

	fehbg
	xcompmgr &

	pkill -u $USER -f pcrd
	pcrctl run daemon

	if [ -f "$HOME/.Xresources" ]; then
		xrdb "$HOME/.Xresources"
	fi

	dwm
done

