# This is a PCRD config file. Lines starting with a hash is are comments.
# You must enable all desired modules manually with Module.enabled=1
# configuration flag. Once a module is enabled, all of its features are enabled
# automatically. If that's not a desired behavior, Module.all_features=0 flag
# can be used.

Power.enabled=1
Performance.enabled=1
Display.enabled=1
Sound.enabled=1
System.enabled=1
Device.enabled=1

Performance.cpu_auto_scaling.enabled=0
Display.xrandr.max_resolution=1920x1080
socket.group=wheel

Status.enabled=1
Status.plugin=1

Dunst.enabled=1
Dunst.plugin=1

Control.enabled=1
Control.plugin=1
Control.gestures.action.u.command=ovoplayerctrl,--playpause
Control.gestures.action.ur.command=ovoplayerctrl,--next
Control.gestures.action.ul.command=ovoplayerctrl,--previous
Control.gestures.action.r.info=Current date,date
Control.gestures.action.ru.command=dunstctl,history-pop
Control.gestures.action.rd.command=dunstctl close-all && dunstctl history-clear
Control.kblayout.layouts.dvorak.layout=pl
Control.kblayout.layouts.dvorak.variant=dvp
Control.kblayout.layouts.dvorak.option=caps:backspace,shift:both_capslock
Control.kblayout.layouts.dvorak.order=0
Control.kblayout.layouts.qwerty.layout=pl
Control.kblayout.layouts.qwerty.option=caps:backspace,shift:both_capslock
Control.kblayout.layouts.qwerty.order=0

Control.wallpapers.default=default.png

Hooker.enabled=1
Hooker.plugin=1
# fix background after changing resolution
Hooker.hook.Display.xrandr.feature=Control,wallpapers,refresh
# caps lock repeat
Hooker.hook.Control.kblayout.command=xset,r,66
Hooker.hook.Device.suspend.command=slock

