# This is a PCRD config file. Lines starting with a hash is are comments.
# You must enable all desired modules manually with Module.enabled=1
# configuration flag. Once a module is enabled, all of its features are enabled
# automatically. If that's not a desired behavior, Module.all_features=0 flag
# can be used.

Power.enabled=1
Performance.enabled=1
Display.enabled=1
Sound.enabled=1
System.enabled=1
Device.enabled=1

Performance.cpu_auto_scaling.enabled=0
Display.xrandr.max_resolution=1920x1080
socket.group=wheel

Status.enabled=1
Status.plugin=1

Dunst.enabled=1
Dunst.plugin=1

Control.enabled=1
Control.plugin=1
Control.gestures.action.u=command,ovoplayerctrl,--playpause
Control.gestures.action.ur=command,ovoplayerctrl,--next
Control.gestures.action.ul=command,ovoplayerctrl,--previous
Control.gestures.action.r=info,Current date,date
Control.gestures.action.ru=command,dunstctl,history-pop
Control.gestures.action.rd=command,dunstctl close-all && dunstctl history-clear

Hooker.enabled=1
Hooker.plugin=1
Hooker.hook.Display.xrandr=fehbg

