Section "InputClass"
	Identifier   "Marble Mouse"
	MatchProduct "Logitech USB Trackball"
	Driver "libinput"
	Option "ScrollMethod"    "button"
	Option "ScrollButton"    "8"
	Option "MiddleEmulation" "true"
EndSection

Section "InputClass"
	Identifier "touchpad"
	MatchIsTouchpad "on"
	MatchDevicePath "/dev/input/event*"
	Driver "libinput"
	Option "Tapping" "on"
	Option "ClickMethod" "clickfinger"
	Option "AccelProfile" "adaptive"
	Option "AccelSpeed" "0.1"
EndSection

