# extra config for slackware desktop

Acpi.enabled=1
Acpi.plugin=1

Device.poweroff.command=init 0
Device.reboot.command=init 6

Power.ac.enabled=0
Power.capacity.enabled=0
Power.charging.enabled=0
Power.charging_threshold.enabled=0
Power.life.enabled=0
Display.brightness.enabled=0
Device.lid.enabled=0
Control.auto_suspend.enabled=0
Control.power.enabled=0

# NOTE: Status plugin needs to have battery dependencies and building commented
# out for now

